arii_git:
    resource: "@AriiGitBundle/Resources/config/routing.yml"
    prefix:   /

arii_homepage:
    pattern:  /
    defaults: {_controller: AriiCoreBundle:Default:index }

arii_home:
    pattern:  /home/{_locale}
    defaults: { _controller: AriiCoreBundle:Default:index }
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp

# ========================================
# Core Bundle
# ----------------------------------------
arii_core:
    resource: "@AriiCoreBundle/Resources/config/routing.yml"
    prefix:   /home/{_locale}
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp

# ========================================
# Tools
# ----------------------------------------
arii_tools:
    resource: "@AriiToolsBundle/Resources/config/routing.yml"
    prefix:   /tools/{_locale}
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp

# ========================================
# JID
# ----------------------------------------
arii_jid:
    resource: "@AriiJIDBundle/Resources/config/routing.yml"
    prefix:   /jid/{_locale}
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp

arii_jid_public:
    resource: "@AriiJIDBundle/Resources/config/routing_public.yml"
    prefix:   /public
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp

arii_jid_nagios:
    resource: "@AriiJIDBundle/Resources/config/routing_nagios.yml"
    prefix:   /nagios
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp

# ========================================
# JOE
# ----------------------------------------
arii_joe:
    resource: "@AriiJOEBundle/Resources/config/routing.yml"
    prefix:   /joe/{_locale}
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp

# ========================================
# MFT
# ----------------------------------------
arii_mft:
    resource: "@AriiMFTBundle/Resources/config/routing.yml"
    prefix:   /mft/{_locale}
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp
# ========================================
# Graphviz
# ----------------------------------------
arii_GVZ:
    resource: "@AriiGraphvizBundle/Resources/config/routing.yml"
    prefix:   /gvz/{_locale}
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp
# ========================================
# Focus
# ----------------------------------------
arii_Focus:
    resource: "@AriiFocusBundle/Resources/config/routing.yml"
    prefix:   /cache
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp

# Appels internes
arii_Internal:
    resource: "@AriiFocusBundle/Resources/config/routing_internal.yml"
    prefix:   /focus
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp

# ========================================
# JOC
# ----------------------------------------
arii_JOC:
    resource: "@AriiJOCBundle/Resources/config/routing.yml"
    prefix:   /joc/{_locale}
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp
# ========================================
# TimeCode
# ----------------------------------------
arii_TC:
    resource: "@AriiTimeBundle/Resources/config/routing.yml"
    prefix:   /tc/{_locale}
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp
# ========================================
# Report
# ----------------------------------------
arii_Report:
    resource: "@AriiReportBundle/Resources/config/routing.yml"
    prefix:   /report/{_locale}
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp
# ----------------------------------------
# Housekeeping
# ----------------------------------------
arii_JID_purge:
    pattern:  /housekeeping/purge
    defaults: { _controller: AriiJIDBundle:DB:purge }

arii_JID_purge_history:
    pattern:  /housekeeping/purge_history
    defaults: { _controller: AriiJIDBundle:DB:purge_history }

arii_JID_purge_order_history:
    pattern:  /housekeeping/purge_order
    defaults: { _controller: AriiJIDBundle:DB:purge_order }

arii_JID_purge_history_out:
    pattern:  /housekeeping/purge/history/{DB}
    defaults: { _controller: AriiJIDBundle:DB:purgeHistory }

arii_JID_purge_orders_history_out:
    pattern:  /housekeeping/purge/orders/{DB}
    defaults: { _controller: AriiJIDBundle:DB:purgeOrdersHistory }

arii_JID_status_history:
    pattern:  /housekeeping/status
    defaults: { _controller: AriiJIDBundle:DB:status }

# ========================================
arii_JID_purge_history_public:
    pattern:  /public/purge/history
    defaults: { _controller: AriiJIDBundle:DB:purge_history }

arii_JID_purge_order_public:
    pattern:  /public/purge/orders
    defaults: { _controller: AriiJIDBundle:DB:purge_order }

arii_JID_purge_order_step_public:
    pattern:  /public/purge/steps
    defaults: { _controller: AriiJIDBundle:DB:purge_order_steps }

# ========================================
# Daily schedule
# ----------------------------------------
arii_ds:
    resource: "@AriiDSBundle/Resources/config/routing.yml"
    prefix:   /plan/{_locale}
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp

# ========================================
# User Bundle
# ----------------------------------------
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password

arii_user:
    resource: "@AriiUserBundle/Resources/config/routing.yml"
    prefix:   /user/{_locale}
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp


# ========================================
# Test Bundle
# ----------------------------------------
