<?php

namespace Proxies\__CG__\Arii\CoreBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UserFilter extends \Arii\CoreBundle\Entity\UserFilter implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Arii\\CoreBundle\\Entity\\UserFilter' . "\0" . 'id', '' . "\0" . 'Arii\\CoreBundle\\Entity\\UserFilter' . "\0" . 'user', '' . "\0" . 'Arii\\CoreBundle\\Entity\\UserFilter' . "\0" . 'name', '' . "\0" . 'Arii\\CoreBundle\\Entity\\UserFilter' . "\0" . 'description', '' . "\0" . 'Arii\\CoreBundle\\Entity\\UserFilter' . "\0" . 'spooler', '' . "\0" . 'Arii\\CoreBundle\\Entity\\UserFilter' . "\0" . 'job', '' . "\0" . 'Arii\\CoreBundle\\Entity\\UserFilter' . "\0" . 'job_chain', '' . "\0" . 'Arii\\CoreBundle\\Entity\\UserFilter' . "\0" . 'order_id', '' . "\0" . 'Arii\\CoreBundle\\Entity\\UserFilter' . "\0" . 'status');
        }

        return array('__isInitialized__', '' . "\0" . 'Arii\\CoreBundle\\Entity\\UserFilter' . "\0" . 'id', '' . "\0" . 'Arii\\CoreBundle\\Entity\\UserFilter' . "\0" . 'user', '' . "\0" . 'Arii\\CoreBundle\\Entity\\UserFilter' . "\0" . 'name', '' . "\0" . 'Arii\\CoreBundle\\Entity\\UserFilter' . "\0" . 'description', '' . "\0" . 'Arii\\CoreBundle\\Entity\\UserFilter' . "\0" . 'spooler', '' . "\0" . 'Arii\\CoreBundle\\Entity\\UserFilter' . "\0" . 'job', '' . "\0" . 'Arii\\CoreBundle\\Entity\\UserFilter' . "\0" . 'job_chain', '' . "\0" . 'Arii\\CoreBundle\\Entity\\UserFilter' . "\0" . 'order_id', '' . "\0" . 'Arii\\CoreBundle\\Entity\\UserFilter' . "\0" . 'status');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (UserFilter $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\Arii\UserBundle\Entity\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setFilter(\Arii\CoreBundle\Entity\Filter $filter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFilter', array($filter));

        return parent::setFilter($filter);
    }

    /**
     * {@inheritDoc}
     */
    public function getFilter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFilter', array());

        return parent::getFilter();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpooler($spooler)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpooler', array($spooler));

        return parent::setSpooler($spooler);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpooler()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpooler', array());

        return parent::getSpooler();
    }

    /**
     * {@inheritDoc}
     */
    public function setJob($job)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJob', array($job));

        return parent::setJob($job);
    }

    /**
     * {@inheritDoc}
     */
    public function getJob()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJob', array());

        return parent::getJob();
    }

    /**
     * {@inheritDoc}
     */
    public function setJobChain($jobChain)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJobChain', array($jobChain));

        return parent::setJobChain($jobChain);
    }

    /**
     * {@inheritDoc}
     */
    public function getJobChain()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJobChain', array());

        return parent::getJobChain();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderId($orderId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderId', array($orderId));

        return parent::setOrderId($orderId);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderId', array());

        return parent::getOrderId();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

}
